#!/bin/bash

VERSION=v11

rm -rf /var/www/html/$VERSION/*
mkdir -p /var/www/html/$VERSION/
echo "{}" > /var/www/html/$VERSION/composer.json
composer config extra.typo3/cms.web-dir public -d /var/www/html/$VERSION
composer config repositories.$EXTENSION_KEY path ../../$EXTENSION_KEY -d /var/www/html/$VERSION
composer config --no-plugins allow-plugins.typo3/cms-composer-installers true -d /var/www/html/$VERSION
composer config --no-plugins allow-plugins.typo3/class-alias-loader true -d /var/www/html/$VERSION
composer req \
    typo3/minimal:'^11.0' \
    typo3/cms-cli:'^3.0' \
    typo3/cms-rte-ckeditor:'^11.0' \
    typo3/cms-belog:'^11.0' \
    typo3/cms-beuser:'^11.0' \
    typo3/cms-info:'^11.0' \
    typo3/cms-lowlevel:'^11.0' \
    typo3/cms-setup:'^11.0' \
    typo3/cms-tstemplate:'^11.0' \
    helhum/typo3-console:'^7.0' \
    $PACKAGE_NAME:'*@dev' \
    --no-progress -n -d /var/www/html/$VERSION

cd /var/www/html/$VERSION

TYPO3_INSTALL_DB_DBNAME=$VERSION
vendor/bin/typo3cms install:setup -n --database-name $VERSION
vendor/bin/typo3cms configuration:set 'BE/debug' 1
vendor/bin/typo3cms configuration:set 'FE/debug' 1
vendor/bin/typo3cms configuration:set 'SYS/devIPmask' '*'
vendor/bin/typo3cms configuration:set 'SYS/displayErrors' 1
vendor/bin/typo3cms configuration:set 'SYS/trustedHostsPattern' '.*.*'
vendor/bin/typo3cms configuration:set 'MAIL/transport' 'smtp'
vendor/bin/typo3cms configuration:set 'MAIL/transport_smtp_server' 'localhost:1025'
vendor/bin/typo3cms configuration:set 'GFX/processor' 'ImageMagick'
vendor/bin/typo3cms configuration:set 'GFX/processor_path' '/usr/bin/'
vendor/bin/typo3cms configuration:set 'GFX/processor_path_lzw' '/usr/bin/'

sed -i -e "s/base: ht\//base: \//g" /var/www/html/$VERSION/config/sites/main/config.yaml
sed -i -e 's/base: \/en\//base: \//g' /var/www/html/$VERSION/config/sites/main/config.yaml

vendor/bin/typo3cms cache:flush

ln -s ../../tailwind_styled_content/src/tailwind.config.js tailwind.config.js
ln -s ../../tailwind_styled_content/src/input.css input.css
ln -s ../../tailwind_styled_content/package.json package.json

ln -s ../../../tailwind_styled_content/src/output.css public/output.css
