services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Jramke\TailwindStyledContent\:
    resource: '../Classes/*'

  Jramke\TailwindStyledContent\Command\TailwindConfigCommand:
    tags:
      - name: console.command
        command: 'tailwind:config'
        description: 'Generates a boilerplate tailwind config file'