name: tailwind-styled-content
type: php
docroot: ""
no_project_mount: true
php_version: "8.2"
composer_version: "2"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames:
    - docs.tailwind-styled-content
    - v11.tailwind-styled-content
    - v12.tailwind-styled-content
    - v13.tailwind-styled-content
additional_fqdns: []
use_dns_when_possible: true
disable_upload_dirs_warning: true
performance_mode: none
web_environment:
    - TYPO3_CONTEXT=Development